import type { NextPage } from 'next';
import Head from 'next/head';
import ChatContainer from '../src/component/ChatContainer';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Chats on <a href="https://nextjs.org">Next.js!</a>
                </h1>
                ChatContainer
            </main>
        </div>
    );
};

export default Home;
